apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: payment-db-deployment
spec:
  serviceName: "payment-db"
  replicas: 1
  selector:
    matchLabels:
      app: payment-db-label
  template:
    metadata:
      labels:
        app: payment-db-label
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
              name: postgredb
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: payment-configmap
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: payment-configmap
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: payment-configmap
                  key: POSTGRES_PASSWORD

          volumeMounts:
            - name: postgredb
              mountPath: /var/lib/postgresql/data
              subPath: postgres

  volumeClaimTemplates:
    - metadata:
        name: postgredb
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
