apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payment-ingress
    #  annotations:
    #    nginx.ingress.kubernetes.io/rewrite-target: /$1
    #заменяет адрес на /$1, где $1 - первая матч-группа из регулярки на 16 и 23 строке
    #например: запрос /actuator/health преобразуется в /health (см. 23 строку)
  #запрос /foo так и останется /foo (см. 16 строку)
spec:
  ingressClassName: nginx
  rules:
    - host: minikube
      http:
        paths:
          - path: /payment
            pathType: Prefix
            backend:
              service:
                name: payment-svc
                port:
                  number: 8013      #должно соответствовать порту сервиса, который в свою очередь указывает на 9090 порт пода

