apiVersion: v1
kind: Service
metadata:
  name: payment-svc
spec:
  selector:
    app: payment-label            #должно соответствовать лейблу пода
  ports:
    - protocol: TCP
      name: web
      port: 8013        #порт сервиса
      targetPort: 8013    #порт пода (порт, который открыт у контейнера)

  type: ClusterIP
  clusterIP: None